services:
  nl-to-logic-ui:
    image: bastiennavarri/nltologic-ui:latest
    container_name: react-ui
    ports:
      - "3000:3000"
    volumes:
      - ./react-ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - nl-to-logic-app

  nl-to-logic-app:
    image: bastiennavarri/nltologic-app-gpu:latest
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - ./models:/models